[package]
name = "wg-vanity"
version = "0.5.1"
edition = "2024"
rust-version = "1.88"
authors = [
    "Shengqi Chen <harry-chen@outlook.com>",
    "Brian Warner <warner@lothar.com>",
]
description = "Find WireGuard keypairs with a specific readable string"
license = "MIT"
readme = "README.md"
categories = ["cryptography"]
documentation = "https://docs.rs/wg-vanity"
homepage = "https://github.com/Harry-Chen/wg-vanity"
repository = "https://github.com/Harry-Chen/wg-vanity"
exclude = [
    "**/.gitignore",
    ".gitignore",
]

[dependencies]
base64 = "0.22"
clap = { version = "4.6", features = ["derive"] }
num_cpus = "1.17"
rayon = "1.12"
regex = "1.11"
x25519-dalek = { version = "3.0", features = ["getrandom", "static_secrets"] }
cudarc = { version = "0.19.9", optional = true, default-features = false, features = ["driver", "nvrtc", "cuda-13030", "fallback-dynamic-loading"] }
mpi = { version = "0.8", optional = true }

[dev-dependencies]
criterion = "0.8"

[features]
default = []
cuda = ["dep:cudarc"]
mpi = ["dep:mpi"]

[lib]
name = "wg_vanity"
path = "src/lib.rs"

[[bin]]
name = "wg-vanity"
path = "src/bin.rs"

[[bin]]
name = "wg-vanity-cuda"
path = "src/bin/cuda.rs"
required-features = ["cuda"]

[[bin]]
name = "wg-vanity-benchmark"
path = "src/bin/benchmark.rs"

[[bench]]
name = "keygen"
harness = false
